### ISSUE TITLE
what is the purpose of mems_id for inference.

### ISSUE THREAD

**Issue by o20021106** [GaoPeng97/transformer-xl-chinese#10]
in your code for inference there are variables such as `new_mems_id` and `mems_id`, but it doesn't seem like they are being used anywhere? Am I wrong, is there a purpose for these variables? Thank you.

**Comment by GaoPeng97** [comment]
Hi, I use them to identify the specific word so that I can output the generation text.  You can find them at line 551/552 in train_gpu.py

**Comment by o20021106** [comment]
Hi, but it doesn't seem like it plays any role in the model. Is its sole purpose visualizing attention?

**Comment by GaoPeng97** [comment]
Yes, you get it.



---Original---

**Comment by o20021106** [comment]
got it. Thank you~
