### ISSUE TITLE
分词之后会提升生成的质量吗

### ISSUE THREAD

**Issue by Qcosmo** [GaoPeng97/transformer-xl-chinese#11]
您好，请问您有尝试过用分词之后的输入去训练模型吗？还有你觉得分词对提升生成的效果有帮助吗？

**Comment by GaoPeng97** [comment]
本身输入是每个字输入+memory得到下一个作为输出，分词后就相当于加了额外的输入信息，可能会对结果有所提升，你可以试一下

**Comment by Qcosmo** [comment]
@GaoPeng97  你好，请问你有用这个模型做过迁移学习吗，我想用在大数据集（20M的txt文档）上训练好的模型作预训练模型去训练一个小数据集（200k的txt）的模型，你觉得可行吗，如果有问题的话，需要注意那些呢？

**Comment by GaoPeng97** [comment]
你好，我不懂迁移学习，可能不能给你什么建议，你可以直接去尝试一下。



---原始邮件---
发件人: "chi cosmo"<notifications@github.com>
发送时间: 2019年7月30日(星期二) 下午3:13
收件人: "GaoPeng97/transformer-xl-chinese"<transformer-xl-chinese@noreply.github.com>;
抄送: "Mention"<mention@noreply.github.com>;"penk"<1329836329@qq.com>;
主题: Re: [GaoPeng97/transformer-xl-chinese] 分词之后会提升生成的质量吗 (#11)



@GaoPeng97  你好，请问你有用这个模型做过迁移学习吗，我想用在大数据集（20M的txt文档）上训练好的模型作预训练模型去训练一个小数据集（200k的txt）的模型，你觉得可行吗，如果有问题的话，需要注意那些呢？

**Comment by Qcosmo** [comment]
那你有试过在小数据集上（几百k的txt）直接训练吗，效果如何

**Comment by GaoPeng97** [comment]
你为什么不自己试一下呢



---原始邮件---
发件人: "chi cosmo"<notifications@github.com>
发送时间: 2019年7月30日(星期二) 下午4:39
收件人: "GaoPeng97/transformer-xl-chinese"<transformer-xl-chinese@noreply.github.com>;
抄送: "Mention"<mention@noreply.github.com>;"penk"<1329836329@qq.com>;
主题: Re: [GaoPeng97/transformer-xl-chinese] 分词之后会提升生成的质量吗 (#11)



那你有试过在小数据集上（几百k的txt）直接训练吗，效果如何

**Comment by Qcosmo** [comment]
试了一下，小数据集上会将内容完全记住，生成的句子基本上都是训练集的原文
