### ISSUE TITLE
ModuleNotFoundError: No module named 'progressbar'

### ISSUE THREAD

**Issue by ldxbaby756** [GaoPeng97/transformer-xl-chinese#12]
处理完数据，训练时候碰到引入这个文件错误，发现这个repo里貌似没有progressbar.py文件，大佬可否提供下？

**Comment by Qcosmo** [comment]
pip install progressbar

**Comment by ldxbaby756** [comment]
看源码有个postprocess，还以为这个是作者实现的，抱歉，打扰了
