### ISSUE TITLE
inference restore model failed

### ISSUE THREAD

**Issue by zhixuhao** [GaoPeng97/transformer-xl-chinese#13]
将模型参数修改为：
#Model
DIV_VAL=1
N_LAYER=6
D_MODEL=500
D_EMBED=500
N_HEAD=10
D_HEAD=50
D_INNER=1000

#Training
TGT_LEN=70
MEM_LEN=70

BSZ=64
NUM_CORE=4

#Testing

TEST_TGT_LEN=70
TEST_MEM_LEN=500
TEST_CLAMP_LEN=400

#TEST_BSZ=10
TEST_BSZ=1

TEST_NUM_CORE=1

跑doupo_base_gpu.sh,训练和eval都是正常的，但是inference的时候报错：
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [4786] rhs shape= [84827]
模型加载不成功，请问是我的参数设置有问题吗

**Comment by zhixuhao** [comment]
发现问题了，doupo下的corpus-info.json文件的vocab size不对，删除重新生成就好了

**Comment by GaoPeng97** [comment]
不好意思 我开始上班了 没有及时关注和回复
