### ISSUE TITLE
知乎数据

### ISSUE THREAD

**Issue by echoyes** [GaoPeng97/transformer-xl-chinese#18]
你好，我想用一下知乎的数据，但是没有找到，请问还有知乎的数据吗？

**Comment by GaoPeng97** [comment]
你好 这是我名字的疏忽 知乎数据在data/test文件夹里面  约20M

**Comment by jianfengzhai** [comment]
可是没有test文件夹哟

**Comment by GaoPeng97** [comment]
不好意思 上次手欠一不小心删了， 你reset 到上一次的commit应该就能找到了。。。
