### ISSUE TITLE
关于中文的预处理

### ISSUE THREAD

**Issue by BlueFishDream** [GaoPeng97/transformer-xl-chinese#19]
大佬，你好，我刚接触这块，想做中文文本摘要的任务，使用transformer框架，对于预处理这块不是很清楚，代码中的处理部分也看了一点，不知道大佬有没有对应讲中文预处理的博客或者资料可以拿来学习的，谢谢啦！

**Comment by GaoPeng97** [comment]
别别 大佬谈不上 我也是小白级别的 关于中文预处理我没有系统的总结过什么资料 一般想看什么 就google一下 资料或者paper还是挺多的

**Comment by BlueFishDream** [comment]
感谢您的回复，我自己也是找中文的项目看，慢慢总结学习。
  
------------------
顺祝时祺！


 




------------------ 原始邮件 ------------------
发件人: "penk"<notifications@github.com>; 
发送时间: 2019年10月16日(星期三) 中午11:06
收件人: "GaoPeng97/transformer-xl-chinese"<transformer-xl-chinese@noreply.github.com>; 
抄送: "zjyDream"<975669552@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [GaoPeng97/transformer-xl-chinese] 关于中文的预处理 (#19)




别别 大佬谈不上 我也是小白级别的 关于中文预处理我没有系统的总结过什么资料 一般想看什么 就google一下 资料或者paper还是挺多的
