### ISSUE TITLE
Where is the zhihu dataset?

### ISSUE THREAD

**Issue by Machine-Tom** [GaoPeng97/transformer-xl-chinese#2]
Hi, very grateful that you share the code & result.
When I work on your code, I can not find the zhihu dataset. Can you please help me with it?

**Comment by GaoPeng97** [comment]
So embarrassed, it is my mistake. test.txt is the zhihu dataset mentioned in readme.  And you should use test_base_gpu.sh( not zhihu_base_gpu.sh) to generate result. BTW, zhihu_base_gpu.sh is for a training on 500M zhihu dataset at first, and model did not converge well on so large a dataset. So I select 20M to get better result.
