### ISSUE TITLE
infernence出现的问题

### ISSUE THREAD

**Issue by DevelMayCry-MrChen** [GaoPeng97/transformer-xl-chinese#21]
Assign requires shapes of both tensors to match. lhs shape= [4786] rhs shape= [84827] 用训练后的模型 进行inference的时候  出现这个错    要改成n_token = 84827#len(tmp_Vocab)   不过改成这样就会预测出问题 训练集保存下来的checkpoint和测试的时候的不一样导致的问题

**Comment by GaoPeng97** [comment]
你好 抱歉回复的比较晚，工作太忙了。 关于这个问题，我没有遇到过，你可以看下readme中说的”注意在inference的时候记得修改train_gpu.py中第504行，改成你想inference的数据集名字“ 有没有修改

**Comment by DevelMayCry-MrChen** [comment]
有的，我按着去做的。也是斗破的数据集。和作者你的一样

**Comment by GaoPeng97** [comment]
那你有试过其他的测试集么，是都会有这个问题么

**Comment by DevelMayCry-MrChen** [comment]
其他数据集没试过  感觉都是差不多的   主要感觉最后一块的输出有点问题   最后一块输出的是所有的字的总和。就是这里感觉有点问题。应该是每个字唯一的id

**Comment by GaoPeng97** [comment]
你是说”input_text += tmp_Vocab.get_sym(index) if tmp_Vocab.get_sym(index) != '<eos>' else '\n'“ 这句么， 这个只是把每次输出的结果合并在一起，是inference的结果的处理，不牵涉到inference的输入

**Comment by GaoPeng97** [comment]
问题已修复 拉最新的commit
