### ISSUE TITLE
如何用transformerXL做文本摘要任务

### ISSUE THREAD

**Issue by Liao-Yong** [GaoPeng97/transformer-xl-chinese#27]
您好，我想请教一下，如果我想用transformerXL模型做文本摘要任务，有什么好的建议吗？

**Comment by GaoPeng97** [comment]
你好，文本摘要我了解的不多，可能给不了什么建议，实在不好意思。（还有个小小的建议，别介意啊，你这么问问题好像不太有信息量，而且感觉好像还没开始做。建议具体点，比如你遇到了什么问题做了怎样的思考以及尝试过什么样的方法，错误的现象是什么，你对现象产生的原因有什么理解，万事开头难，先做起来再说）仅仅是建议，无意冒犯，溜了溜了。
