### ISSUE TITLE
seed text干什么用的？

### ISSUE THREAD

**Issue by aazjcom** [GaoPeng97/transformer-xl-chinese#29]
seed text干什么用的？
结果文件保存在哪里？
train_steps=1000000,你花了多少时间，用gpu的吗

**Comment by GaoPeng97** [comment]
论文读了么？
实验跑了么？
代码看了么？

**Comment by aazjcom** [comment]
代码跑过了，train_steps=1000000，这个值太大了，太耗时间了。没有用gpu，太贵了。

**Comment by GaoPeng97** [comment]
seed_text 就相当于给的引子，让模型接着往下写内容。
结果我记得我没有写保存，直接输出在命令行窗口
我的结果都是用1080ti跑的， 具体时间的话可以参考 issue5 https://github.com/GaoPeng97/transformer-xl-chinese/issues/5
那个train_steps 也可以改小一点啦，结果可能也还好，你可以试一下，设置一个你能接受的看一下结果是否符合你的期待。加油

**Comment by aazjcom** [comment]
谢谢，果然有钱。

**Comment by GaoPeng97** [comment]
主要是在公司做的，反正也不烧自己的钱。。。

**Comment by aazjcom** [comment]
哈哈，公司也很有钱啊。
