### ISSUE TITLE
你好，我发了邮件给gp2015@mail.ustc.edu.cn，请查看下哦

### ISSUE THREAD

**Issue by 1397981186** [GaoPeng97/transformer-xl-chinese#31]
我有几个问题请教一下
     1.我目前任务是针对一些文本生成他的关键词，不单单是简单的抽取，而是要有语义上的理解，比如说“王某偷窃十万元”-“偷窃罪”，请问能否直接训练“文本”-“关键词”达到效果
     2.关于中文预处理的部分，请问具体在代码的哪个部分，data_utils_chinese.py吗

**Comment by RingoTC** [comment]
可以用copynet 达到这个效果
