### ISSUE TITLE
能加一下你的微信吗，有些问题想请教一下

### ISSUE THREAD

**Issue by DevilEEE** [GaoPeng97/transformer-xl-chinese#4]

**Comment by GaoPeng97** [comment]
emmm 有什么事么 你可以直接在这里说， 或者发邮件给我gp2015@mail.ustc.edu.cn

**Comment by speeding-motor** [comment]
哈喽，我想问一下，listwise排序里的，通过计算不同排列组合的概率然后计算交叉熵进行训练这块你是怎么做的啊，我最近一直在研究这个，没得出好的解决方法

**Comment by DevilEEE** [comment]
没这么做过


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: jiasudemotuohe <notifications@github.com>
发送时间: 2019年8月1日 23:46
收件人: GaoPeng97/transformer-xl-chinese <transformer-xl-chinese@noreply.github.com>
抄送: wang fudong <1114661762@qq.com>, Author <author@noreply.github.com>
主题: 回复：[GaoPeng97/transformer-xl-chinese] 能加一下你的微信吗，有些问题想请教一下 (#4)




哈喽，我想问一下，listwise排序里的，通过计算不同排列组合的概率然后计算交叉熵进行训练这块你是怎么做的啊，我最近一直在研究这个，没得出好的解决方法
