### ISSUE TITLE
您用了怎么样的设备，训练了多长时间呢

### ISSUE THREAD

**Issue by kidsbmilk** [GaoPeng97/transformer-xl-chinese#5]

**Comment by GaoPeng97** [comment]
你好 设备都是1080Ti 显卡
斗破苍穹小说：两张卡 训练了43h
知乎数据：四张卡 110h
古诗：四张卡 65小时

**Comment by kidsbmilk** [comment]
感谢您的回复~
另外，我目前有15万左右的论文-摘要数据集，包含各个方向、领域的论文，每篇论文字数在500-1500字左右，摘要在100-300字左右，我想用它训练一个长摘要模型，我想使用您这个transformer-xl-chinese来做，您觉得可行吗？或者，您有什么更好的建议吗？

**Comment by GaoPeng97** [comment]
您好，我在邮件里回复您了，查收一下

**Comment by caorongzhe** [comment]
电脑运行，直接卡死，有什么可优化的方案吗

**Comment by GaoPeng97** [comment]
> 电脑运行，直接卡死，有什么可优化的方案吗

可能是显卡内存炸了，你可以试试改小一下bsz，或者memory_len

**Comment by maozezhong** [comment]
@kidsbmilk HI, 请问repo作者是什么建议呢？我也有个类似的生成标题的任务
@GaoPeng97
