### ISSUE TITLE
请问模型训练的终止条件是什么？

### ISSUE THREAD

**Issue by xinyx** [GaoPeng97/transformer-xl-chinese#6]
LM是根据training loss还是validation loss判断模型性能呢？
我看之前的issue，说模型要训练40~60h，这样我认为training loss会降得很低直至收敛，而训练后期的valid loss应该是上升的。不知如何判断模型好坏，以及inference时用的是training data还是valid data？
谢谢！

**Comment by GaoPeng97** [comment]
你好 很抱歉没能及时回复，我在判断终止条件的时候主要是根据训练的loss，没有用到valid，还有就是直接测试已生成模型看效果是否满意。

**Comment by xinyx** [comment]
谢谢GaoPeng97！

我在尝试用新数据集训练模型。我看repo中poetry和zhihu数据集分别是**4.5M和20M**，而我的诗歌和文章数据集分别是**18M和180M**，用repo提供的参数发现收敛后的模型生成效果很差，比如“秋天的风吹来，吹落了一地的落叶，吹落了一地的落叶，吹落了一地的落叶，...“。

请问是否清楚可能的原因是什么？（e.g. 数据太大导致不能拟合？但我的诗歌18M与知乎20M是等量级的）

我诗歌和文章收敛的loss是~2.0和~3.0，这loss是否太大？

**Comment by GaoPeng97** [comment]
你好，我也遇到过这种问题。我谈谈自己的看法，仅供参考。

首先对于诗歌而言，不知道你用的是现代诗还是古诗，如果是古诗的话，其实不需要loss太低也可以得到比较好的效果，因为训练任务中是根据当前给定输入预测下一个输出，句子的通顺性很重要，但是古诗不通顺也没太大关系，重要的是押韵和对仗。若是现代诗则要求就会高一点，因为通顺是必要的。

其次就是你生成的这种输出重复性问题，这个是文本生成任务中一个非常常见的问题，但是如何解决还没有非常可信的方法，一般的建议是加深训练的程度，比如调大迭代次数之类的，也就是你说的可能没有拟合。往往数据集越大需要训练的程度就要越大。比如，对于知乎数据我曾经尝试用500M的数据进行训练，八张卡训练了一周多，生成结果还是会有很多重复。然后换成20M左右的却可以得到比较好的结果（不太重复）。

最后，关于loss能不能反映生成结果的优良，一定程度上当然是可以的。但是仔细思考一下，我们的目的是生成比较通顺的语句而且前后要有一定的逻辑关系。通顺这个事情很难描述，同样的输入加上不同的输出都有可能通顺，对于我们的训练任务，如果输出结果与指定的label不同就会带来loss，这其实就有点不合理了。逻辑性则更难衡量了。所以我的观点是要客观的看待loss与输出结果质量的关系，对于生成问题，多依赖于主观判断无可厚非。

**Comment by xinyx** [comment]
多谢解释，受教！（p.s. 我用的是现代诗）

其实同样的数据我也用多层LSTM试过，跟transformer-xl参数量差不多，但只用单1080TI卡，~12h就收敛了，并且几乎没有重复的，如（秋天的风吹来，风像雨点樱花 火热的丢大海，你在海上点头节拍，看淡出的我 深入湖海村外，跳舞的姿态 你扰乱了裙摆，追着信念带我飞向未来）。

相比于你的1week/8卡，用LSTM做LM的训练性价比实在高很多，但是最优解是弱于Transformer-xl的（起码从loss看，LSTM Loss >> Transformer-xl Loss）。

所以或许可以这么总结，在LM中，LSTM-based models的model collapse现象较轻，但transformer-based models的最优解更好，同时收敛难度更高。

**Comment by GaoPeng97** [comment]
嗯，我觉得你总结的是有道理的。
感觉transformer xl训练难度较大，可能是因为不像LSTM等收到梯度消逝或爆炸的影响导致记忆长度较短，而transformer xl由于memory len较长，要处理的条件概率情况就复杂得多，所以生成质量在排除重复性后，应该会更高。
PS：你可以尝试下，在transformer xl的输出采取前几个置信度较高的字，random一下，看下结果如何。
