### ISSUE TITLE
训练，验证，推理时指定的模型文件不一样

### ISSUE THREAD

**Issue by fengzuo97** [GaoPeng97/transformer-xl-chinese#7]
在doupo_base_gpu.sh文件中，训练，验证，推理指定的model_dir文件加名字不一样，在训练wt103时，验证数据集用的enwiki8?感觉有点混乱

**Comment by GaoPeng97** [comment]
你好，抱歉没有及时回复，这个代码是基于原来的transformer xl， script也是直接基于transformer-xl中的script进行得修改，所以代码会有很多不干净的地方，因为我只用到了train 和 inference的部分，所以valid和eval基本上没有一并改掉（因为做毕设比较赶时间）。
