### ISSUE TITLE
请问预测过程又可以优化执行时间的方法吗

### ISSUE THREAD

**Issue by Qcosmo** [GaoPeng97/transformer-xl-chinese#9]
我在训练好模型后，使用inference函数做推断时，发现你的代码逻辑是每次预测一个字，然后不断迭代200次，每次计算的时间约为0.5s（在gpu环境下做的推测，用的p40的卡），我看一些资料说xl对速度做了优化，可以输入[1,2,3,4]得出[5,6,7,8],如果我想每次迭代时预测后续多个汉字应该修改哪里呢？这样做对速度提升有帮助吗？

**Comment by GaoPeng97** [comment]
我感觉这个生成任务应该没法达到你说的直接并行的预测出 [5, 6, 7, 8]，毕竟每次生成都要用该字之前的所有字做推断。所以我觉得在做单句生成时，做不了并行。同时生成多句倒是应该可以。这个你就要修改一下输入的尺寸，然后后面整个inference的逻辑我都是基于单句做的，应当都要改动。

**Comment by Qcosmo** [comment]
好的，谢谢了，我试一下
